CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY, 
    BOOK_NAME VARCHAR(20) NOT NULL,
    AUTHOR_NAME VARCHAR(20) NOT NULL
);

SELECT * FROM BOOKS;

ALTER TABLE BOOKS
ADD BOOK_COUNT INT CHECK (BOOK_COUNT > 0) NOT NULL;

INSERT INTO BOOKS 
VALUES (202, 'Atomic Habits', 'James Clear', 6);

SELECT * FROM BOOKS;

CREATE TABLE LIBRARY_VISITORS (
    USER_ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    AGE INT CHECK (AGE >= 17) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL UNIQUE
);

SELECT * FROM LIBRARY_VISITORS;

INSERT INTO LIBRARY_VISITORS (USER_ID, NAME, AGE, EMAIL) 
VALUES (601, 'Rahul', 21, 'rahul21@gmail.com');

SELECT * FROM LIBRARY_VISITORS;

CREATE TABLE BOOK_ISSUE (
    BOOK_ISSUE_ID INT PRIMARY KEY,
    BOOK_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES LIBRARY_VISITORS(USER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

INSERT INTO BOOK_ISSUE 
VALUES (11001, 202, 601);

ALTER TABLE BOOK_ISSUE
ADD ISSUE_DATE DATE;

SELECT * FROM BOOK_ISSUE;

UPDATE BOOK_ISSUE
SET ISSUE_DATE = '2026-02-12'
WHERE BOOK_ID = 202;

SELECT * FROM BOOK_ISSUE;

CREATE ROLE LIBRARIAN 
WITH LOGIN PASSWORD 'library@123';

SELECT CURRENT_USER;

GRANT SELECT, INSERT, DELETE, UPDATE ON BOOKS TO LIBRARIAN;
GRANT SELECT, INSERT, DELETE, UPDATE ON BOOK_ISSUE TO LIBRARIAN;
GRANT SELECT, INSERT, DELETE, UPDATE ON LIBRARY_VISITORS TO LIBRARIAN;

SELECT * FROM BOOKS;
SELECT * FROM BOOK_ISSUE;
SELECT * FROM LIBRARY_VISITORS;

REVOKE SELECT, INSERT, DELETE, UPDATE 
ON BOOKS, BOOK_ISSUE, LIBRARY_VISITORS 
FROM LIBRARIAN;

SELECT * FROM BOOKS;

TRUNCATE TABLE BOOK_ISSUE;

SELECT * FROM BOOK_ISSUE;

DROP TABLE BOOK_ISSUE;

SELECT * FROM BOOK_ISSUE;
